### PR TITLE
Multi fetch needs the array of keys splatted.

### PR DESCRIPTION
**Pull request by rovermicrover**
In reference to this other PR https://github.com/jsonapi-rb/jsonapi-renderer/pull/28

### CODE REVIEW

**Comment by beauby** [comment]
Thanks for the PR :+1:. You'll probably need to add a splat [there](https://github.com/jsonapi-rb/jsonapi-renderer/blob/master/spec/caching_spec.rb#L8) as well for the tests to pass. 

LGTM otherwise.

**Comment by rovermicrover** [comment]
Well aren't I stupid/lazy. I fixed that on the last PR and completely forgot about it my bad.

**Comment by beauby** [comment]
Perfect, thanks! Merging

**Comment by samnang** [comment]
@beauby any chance to get a new release that contains this fix?

**Pull request merged**
